version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "instaplus-backend"
s3_prefix = "instaplus-backend"
region = "us-west-2"
profile = "ammaar"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
s3_bucket = "instaplus-sam"
