AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  Layers:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: Layers
      ContentUri: src/lambda/layers/
      CompatibleRuntimes:
        - nodejs14.x
  
  UsersPost:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/lambda/users/
      Handler: src/lambda/users/app.handler
      Runtime: nodejs14.x
      Layers:
        - !Ref Layers
      Events:
        UsersApi:
          Type: Api
          Properties:
            Path: /users
            Method: get
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
        - app.ts
  
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  InstaPlusApi:
    Description: API Gateway endpoint URL for Prod stage for Insta Plus function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
   
