# AWSTemplateFormatVersion: '2010-09-09'
# Transform: AWS::Serverless-2016-10-31
# Globals:
#   Function:
#     Runtime: nodejs14.x
#     Timeout: 10

# Resources:

#   AuthorizationApiGateway:
#     Type: AWS::Serverless::Api
#     Properties:
#       StageName: Prod
#       Auth:
#         DefaultAuthorizer: MyLambdaTokenAuthorizer
#         Authorizers:
#           MyLambdaTokenAuthorizer:
#             FunctionPayloadType: TOKEN
#             FunctionArn: !GetAtt testFunc.Arn
#   testFunc:
#     Type: AWS::Serverless::Function
#     Properties:
#       CodeUri: src/lambda/authorizer/
#       Handler: src/lambda/authorizer/auth.handler
#       Runtime: nodejs14.x
#       Events:
#         GetRoot:
#           Type: Api
#           Properties:
#             RestApiId: !Ref AuthorizationApiGateway
#             Path: /auth
#             Method: get
#     Metadata: # Manage esbuild properties
#       BuildMethod: esbuild
#       BuildProperties:
#         Minify: true
#         Target: es2020
#         Sourcemap: true
#         EntryPoints:
#           - auth.ts
#   # Authorizer:
#   #   Type: AWS::Serverless::Function
#   #   Properties:
#   #     CodeUri: src/lambda/authorizer/
#   #     Handler: auth.handler
#   #     Runtime: nodejs14.x
#   #   Metadata: # Manage esbuild properties
#   #     BuildMethod: esbuild
#   #     BuildProperties:
#   #       Minify: true
#   #       Target: es2020
#   #       Sourcemap: true
#   #       EntryPoints:
#   #         - auth.ts
#   Layers:
#     Type: AWS::Serverless::LayerVersion
#     Properties:
#       LayerName: Layers
#       ContentUri: src/lambda/layers/
#       CompatibleRuntimes:
#         - nodejs14.x
#   UsersPost:
#     Type: AWS::Serverless::Function
#     Properties:
#       CodeUri: src/lambda/users/
#       Handler: src/lambda/users/app.handler
#       Runtime: nodejs14.x
#       Layers:
#         - !Ref Layers
#       Events:
#         UsersApi:
#           Type: Api
#           Properties:
#             Path: /users
#             Method: get
#             RestApiId: !Ref AuthorizationApiGateway
#             Auth:
#               Authorizer: testFunc
#               # Authorizer: MyLambdaTokenAuthorizer
#     Metadata: # Manage esbuild properties
#       BuildMethod: esbuild
#       BuildProperties:
#         Minify: true
#         Target: es2020
#         Sourcemap: true
#         EntryPoints:
#         - app.ts

# Outputs:
#   # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
#   # Find out more about other implicit resources you can reference within SAM
#   # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
#   InstaPlusApi:
#     Description: API Gateway endpoint URL for Prod stage for Insta Plus function
#     Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"

AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    Runtime: nodejs14.x
    Timeout: 100

Resources:
  Authorizer:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/lambda/authorizer/
      Handler: src/lambda/authorizer/auth.handler
      Runtime: nodejs14.x
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - auth.ts

  AuthorizationApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Auth:
        DefaultAuthorizer: Authorizer  # Updated the authorizer name here
        Authorizers:
          Authorizer:  # Updated the authorizer name here
            FunctionPayloadType: TOKEN
            FunctionArn: !GetAtt Authorizer.Arn

  Layers:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: Layers
      ContentUri: src/lambda/layers/
      CompatibleRuntimes:
        - nodejs14.x

  InstallmentCrud:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/lambda/installmentService/
      Handler: src/lambda/installmentService/app.handler
      Runtime: nodejs14.x
      MemorySize: 128
      Layers:
        - !Ref Layers
      Events:
        UsersApi:
          Type: Api
          Properties:
            Path: /installment
            Method: Post
            # RestApiId: !Ref AuthorizationApiGateway
            # Auth:
            #   Authorizer: Authorizer
            #   AuthorizationScopes:  
            #   - user.read  # Updated the authorizer name here
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - app.ts
  
  InstallmentPlanCrud:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/lambda/planService/
      Handler: src/lambda/planService/app.handler
      Runtime: nodejs14.x
      MemorySize: 128
      Layers:
        - !Ref Layers
      Events:
        UsersApi:
          Type: Api
          Properties:
            Path: /plan
            Method: Post
            # RestApiId: !Ref AuthorizationApiGateway
            # Auth:
            #   Authorizer: Authorizer
            #   AuthorizationScopes:  
            #   - user.read  # Updated the authorizer name here
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - app.ts

  GaurantorCrud:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/lambda/gurantorService/
      Handler: src/lambda/gurantorService/app.handler
      Runtime: nodejs14.x
      MemorySize: 128
      Layers:
        - !Ref Layers
      Events:
        UsersApi:
          Type: Api
          Properties:
            Path: /gurantor
            Method: Post
            # RestApiId: !Ref AuthorizationApiGateway
            # Auth:
            #   Authorizer: Authorizer
            #   AuthorizationScopes:  
            #   - user.read  # Updated the authorizer name here
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - app.ts
  ProductCrud:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/lambda/productService/
      Handler: src/lambda/productService/app.handler
      Runtime: nodejs14.x
      MemorySize: 128
      Layers:
        - !Ref Layers
      Events:
        UsersApi:
          Type: Api
          Properties:
            Path: /product
            Method: Post
            # RestApiId: !Ref AuthorizationApiGateway
            # Auth:
            #   Authorizer: Authorizer
            #   AuthorizationScopes:  
            #   - user.read  # Updated the authorizer name here
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - app.ts

  SubscriptionCrud:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/lambda/subscriptionService/
      Handler: src/lambda/subscriptionService/app.handler
      Runtime: nodejs14.x
      MemorySize: 64
      Layers:
        - !Ref Layers
      Events:
        UsersApi:
          Type: Api
          Properties:
            Path: /subscription
            Method: Post
            # RestApiId: !Ref AuthorizationApiGateway
            # Auth:
            #   Authorizer: Authorizer
            #   AuthorizationScopes:  
            #   - user.read  # Updated the authorizer name here
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - app.ts

  Search:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/lambda/search/
      Handler: src/lambda/search/app.handler
      Runtime: nodejs14.x
      MemorySize: 512
      Layers:
        - !Ref Layers
      Events:
        UsersApi:
          Type: Api
          Properties:
            Path: /search
            Method: Get
            # RestApiId: !Ref AuthorizationApiGateway
            # Auth:
            #   Authorizer: Authorizer
            #   AuthorizationScopes:  
            #   - user.read  # Updated the authorizer name here
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - app.ts
  
  GetSubscriptions:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/lambda/getSubscriptions/
      Handler: src/lambda/getSubscriptions/app.handler
      Runtime: nodejs14.x
      MemorySize: 512
      Timeout: 30
      Layers:
        - !Ref Layers
      Events:
        UsersApi:
          Type: Api
          Properties:
            Path: /getSubscriptions
            Method: Get
            # RestApiId: !Ref AuthorizationApiGateway
            # Auth:
            #   Authorizer: Authorizer
            #   AuthorizationScopes:  
            #   - user.read  # Updated the authorizer name here
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - app.ts

  DocumentCrud:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/lambda/documentService/
      Handler: src/lambda/documentService/app.handler
      Runtime: nodejs14.x
      MemorySize: 128
      Layers:
        - !Ref Layers
      Events:
        UsersApi:
          Type: Api
          Properties:
            Path: /document
            Method: Post
            # RestApiId: !Ref AuthorizationApiGateway
            # Auth:
            #   Authorizer: Authorizer
            #   AuthorizationScopes:  
            #   - user.read  # Updated the authorizer name here
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - app.ts
  
  UsersPost:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/lambda/users/
      Handler: src/lambda/users/app.handler
      Runtime: nodejs14.x
      MemorySize: 1024
      Layers:
        - !Ref Layers
      Events:
        UsersApi:
          Type: Api
          Properties:
            Path: /users
            Method: Post
            # RestApiId: !Ref AuthorizationApiGateway
            # Auth:
            #   Authorizer: None
            #   AuthorizationScopes:  
            #   - user.read  
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - app.ts

Outputs:
  InstaPlusApi:
    Description: API Gateway endpoint URL for Prod stage for Insta Plus function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
